repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.patch'
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.8
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.4
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.174.0
    hooks:
      - id: renovate-config-validator
