name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

# limit rapid succession from pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - esxi-img
          - esxi-netinit

    environment:
      name: pypi
      url: https://pypi.org/p/${{ matrix.package }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.4"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          pyproject-file: "pyproject.toml"

      - run: uv build --package ${{ matrix.package }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
